

export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SELECT_CATEGORY: 'SELCET_CATEGORY',
  SET_PRICE: 'SET_PRICE',
  SET_SORT: 'SET_SORT',
  SET_SEARCH: 'SET_SEARCH'
}